services:
  - type: web
    name: ts2
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    branch: remote
    healthCheckPath: /
    disk:
      name: ts2-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 10000
      - key: TS2_WORKSPACE
        value: /data
