# 原子：_build_parser（原 plan_cli.py 第 1483 行）
# 由 split_atoms.py 机械生成，勿手改。
from __future__ import annotations

def _build_parser() -> argparse.ArgumentParser:
    """构建完整 argparse 树（供 main 执行与 doc 自举导出共用）。"""
    ap = argparse.ArgumentParser(description="Plan 文档结构化 CLI（Agent 直接填 API，对齐 writing-plans 规范）")
    ap.add_argument("--db", default=str(PLANS_DB), help=f"SQLite 路径（默认 {PLANS_DB}）")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("create", help="创建 plan")
    p.add_argument("--title", required=True)
    p.add_argument("--goal", default="")
    p.add_argument("--arch", default="", help="架构/方案（2-3 句）")
    p.add_argument("--stack", default="", help="技术栈")
    p.add_argument("--global-constraints", default="",
                   help="项目级硬约束（writing-plans Global Constraints），每行一条，`n 分隔")

    sub.add_parser("list", help="列出 plans")

    p = sub.add_parser("update", help="更新 plan")
    p.add_argument("--id", type=int, required=True)
    p.add_argument("--status", choices=("open", "done", "cancelled"))
    p.add_argument("--title")
    p.add_argument("--goal")
    p.add_argument("--arch")
    p.add_argument("--stack")
    p.add_argument("--global-constraints")

    p = sub.add_parser("delete", help="删除 plan（含任务/步骤）")
    p.add_argument("--id", type=int, required=True)

    p = sub.add_parser("task", help="任务操作")
    tsub = p.add_subparsers(dest="tcmd", required=True)
    ta = tsub.add_parser("add")
    ta.add_argument("--plan", type=int, required=True)
    ta.add_argument("--title", required=True)
    ta.add_argument("--detail", default="")
    ta.add_argument("--files", default="", help="文件清单，每行 'Create:/Modify:/Test: 路径'，用 `n 分隔")
    ta.add_argument("--req", default="", help="关联需求，格式 kind:name（如 path:/api/agent/chat/stream）")
    ta.add_argument("--defect", default="", help="关联静态缺陷，格式 dim:file:line:kind（如 flag:app.py:1140:clear_without_set）")
    ta.add_argument("--interfaces", default="",
                    help="任务接口（writing-plans Interfaces）：Consumes/Produces，每行一条，`n 分隔")
    tl = tsub.add_parser("list")
    tl.add_argument("--plan", type=int, required=True)
    tu = tsub.add_parser("update")
    tu.add_argument("--id", type=int, required=True)
    tu.add_argument("--status", choices=("open", "done", "cancelled"))
    tu.add_argument("--title")
    tu.add_argument("--detail")
    tu.add_argument("--files")
    tu.add_argument("--req")
    tu.add_argument("--defect")
    tu.add_argument("--interfaces")
    td = tsub.add_parser("delete")
    td.add_argument("--id", type=int, required=True)

    ts = tsub.add_parser("step", help="任务步骤（TDD 闭环）")
    ssub = ts.add_subparsers(dest="scmd", required=True)
    sa = ssub.add_parser("add")
    sa.add_argument("--task", type=int, required=True)
    sa.add_argument("--text", required=True, help="步骤描述")
    sa.add_argument("--action", choices=("test", "implement", "run", "commit", "other"), default="other")
    sa.add_argument("--code", default="", help="步骤内代码块内容")
    sa.add_argument("--lang", default="", help="代码块语言（python/bash/...）")
    sa.add_argument("--run", default="", help="运行命令")
    sa.add_argument("--expected", default="", help="预期输出")
    sl = ssub.add_parser("list")
    sl.add_argument("--task", type=int, required=True)
    su = ssub.add_parser("update")
    su.add_argument("--id", type=int, required=True)
    su.add_argument("--status", choices=("open", "done"))
    su.add_argument("--text")
    su.add_argument("--action", choices=("test", "implement", "run", "commit", "other"))
    su.add_argument("--code")
    su.add_argument("--lang")
    su.add_argument("--run")
    su.add_argument("--expected")
    sd = ssub.add_parser("delete")
    sd.add_argument("--id", type=int, required=True)

    p = sub.add_parser("export", help="导出 plan.md + json")
    p.add_argument("--id", type=int, required=True)
    p.add_argument("--out", default="", help="输出路径（默认 mcp/docs/PLAN_<id>.md）")
    p.add_argument("--format", choices=("writing-plans", "table"), default="writing-plans",
                   help="导出格式（默认 writing-plans，对齐 writing-plans skill）")

    p = sub.add_parser("tdd", help="TDD 合规性检查")
    tdd_sub = p.add_subparsers(dest="tdd_cmd", required=True)
    tc = tdd_sub.add_parser("check", help="检查任务的 TDD 闭环（Red→Green→Refactor）")
    tc.add_argument("--plan", type=int, default=0, help="按 plan 范围检查")
    tc.add_argument("--task", type=int, default=0, help="按单个 task 检查")

    p = sub.add_parser("verify", help="完成门禁（verification-before-completion）")
    p.add_argument("--plan", type=int, required=True, help="检查的 plan id")

    p = sub.add_parser("ledger", help="进度台账（executing-plans/sdd 跨会话恢复）")
    p.add_argument("--plan", type=int, required=True)
    p.add_argument("--out", default="", help="输出路径（默认 mcp/docs/plan_<id>_progress.md）")

    p = sub.add_parser("review", help="review 循环状态机（requesting/receiving-code-review）")
    p.add_argument("--task", type=int, required=True, help="任务 id")
    p.add_argument("--action", required=True, choices=("request", "approve", "reject", "fix"),
                   help="request=提交审查 / approve=spec+quality 通过 / reject=打回含 findings / fix=修复后重新提交")
    p.add_argument("--findings", default="", help="reject 时的发现项（Critical/Important/Minor，`n 分隔）")

    p = sub.add_parser("dispatch", help="并行任务派发（dispatching-parallel-agents）")
    p.add_argument("--plan", type=int, required=True)

    p = sub.add_parser("defect", help="静态缺陷联动（extractor index.json）")
    dsub = p.add_subparsers(dest="defect_cmd", required=True)
    dl = dsub.add_parser("list", help="列出静态缺陷（可绑定到任务 --defect）")
    dl.add_argument("--index", default=str(INDEX_JSON))
    dg = dsub.add_parser("gen-test", help="生成回归测试文件（Agent 通过接口写测试文件，补强静态缺陷）")
    dg.add_argument("--task", type=int, required=True, help="绑定了静态缺陷的任务 id")
    dg.add_argument("--out", default="", help="输出测试文件路径（默认 tests/test_defect_*.py）")
    dg.add_argument("--index", default=str(INDEX_JSON), help="extractor 索引路径")

    p = sub.add_parser("chain", help="接口链路查询（读取 extractor 产出的 interface_chain.db / index.json，替代 grep）")
    csub = p.add_subparsers(dest="chain_cmd", required=True)
    cs = csub.add_parser("stats", help="运行统计（stats 表）")
    cs.add_argument("--db", default=str(DOCS_DIR / "interface_chain.db"))
    ci = csub.add_parser("issues", help="缺陷查询（defuse/behavior/flag/merge，可过滤）")
    ci.add_argument("--db", default=str(DOCS_DIR / "interface_chain.db"))
    ci.add_argument("--kind", default="", help="缺陷类型过滤（no_assignment/loose_match/external_contract/clear_without_set/...）")
    ci.add_argument("--file", default="", help="文件路径过滤（子串）")
    ci.add_argument("--attr", default="", help="属性名过滤（子串）")
    ci.add_argument("--count", action="store_true", help="按缺陷类型计数分布（defuse/flag/merge/id_source/behavior）")
    ce = csub.add_parser("endpoints", help="端点查询")
    ce.add_argument("--db", default=str(DOCS_DIR / "interface_chain.db"))
    ce.add_argument("--path", default="", help="路径过滤（子串）")
    ce.add_argument("--func", default="", help="函数名过滤（子串）")
    ce.add_argument("--no-model", action="store_true", help="仅列出无请求模型的端点（入参未校验候选）")
    ce.add_argument("--by-file", action="store_true", help="按文件分组统计端点数")
    cm = csub.add_parser("models", help="请求模型字段查询")
    cm.add_argument("--db", default=str(DOCS_DIR / "interface_chain.db"))
    cm.add_argument("--name", default="", help="模型名过滤")
    cm.add_argument("--dup", action="store_true", help="跨文件重复模型定义（后定义覆盖先定义风险）")
    cd = csub.add_parser("drifts", help="前后端漂移（drifts 表）")
    cd.add_argument("--db", default=str(DOCS_DIR / "interface_chain.db"))
    ct = csub.add_parser("tables", help="库表结构与行数（复用 _query_interface_db 逻辑）")
    ct.add_argument("--db", default=str(DOCS_DIR / "interface_chain.db"))

    p = sub.add_parser("doc", help="自举导出本 CLI 的命令文档（markdown，从 argparse 定义生成）")
    p.add_argument("--out", default=str(MCP_ROOT / "docs" / "PLAN_CLI.md"),
                   help="输出 markdown 路径")

    p = sub.add_parser("openspec", help="OpenSpec 桥接（openspec-propose/apply-change/explore/sync-specs 机器化）")
    osub = p.add_subparsers(dest="openspec_cmd", required=True)
    ol = osub.add_parser("list", help="列出 changes（openspec-explore）")
    ol.add_argument("--cwd", default="", help="openspec 根目录（默认项目根）")
    os_ = osub.add_parser("status", help="change 的 artifacts 完成度 + tasks 进度（openspec-explore）")
    os_.add_argument("--change", required=True)
    os_.add_argument("--cwd", default="")
    oi = osub.add_parser("import", help="导入 change 的 tasks.md 为 plan/task（openspec-propose）")
    oi.add_argument("--change", required=True)
    oi.add_argument("--plan", type=int, default=0, help="目标 plan id（缺省自动创建）")
    oi.add_argument("--cwd", default="")
    oe = osub.add_parser("export", help="把 plan 的 task 完成状态回写 tasks.md checkbox（openspec-apply-change）")
    oe.add_argument("--change", required=True)
    oe.add_argument("--plan", type=int, required=True)
    oe.add_argument("--cwd", default="")
    oss = osub.add_parser("sync-specs", help="delta specs → requirements 条目（openspec-sync-specs）")
    oss.add_argument("--change", required=True)
    oss.add_argument("--cwd", default="")
    return ap
