import type { SubtitlesStreamInfo } from '../plugins/bridge'

export function getSubtitleIndexBy(
  subtitles: SubtitlesStreamInfo[],
  preferredLang = 'zh',
): number {
  if (!subtitles.length) return -1
  const idx = subtitles.findIndex(
    s => s.languageCode?.startsWith(preferredLang) && !s.autoGenerated,
  )
  if (idx >= 0) return idx
  const autoIdx = subtitles.findIndex(s => s.languageCode?.startsWith(preferredLang))
  if (autoIdx >= 0) return autoIdx
  const firstManual = subtitles.findIndex(s => !s.autoGenerated)
  return firstManual >= 0 ? firstManual : 0
}
