<template>
  <div
    class="player-view"
    @touchstart="onTouchStart"
    @touchmove="onTouchMove"
    @touchend="onTouchEnd"
    :style="{ transform: swipeOffset > 0 ? `translateY(${swipeOffset}px)` : '', opacity: swipeOpacity, transition: swiping ? 'none' : 'transform 0.2s, opacity 0.2s' }"
  >
    <div v-if="loading" class="loading">加载视频信息{{ loadAttempt > 0 ? ` (第 ${loadAttempt} 次尝试)` : '' }}...</div>
    <div v-else-if="error" class="error-panel">
      <div class="error-icon">⚠️</div>
      <div class="error-text">{{ error }}</div>
      <button v-if="showRetryButton" class="retry-btn" @click="retry">🔄 重试</button>
    </div>
    <template v-else-if="info">
      <div class="video-container" ref="videoContainerRef">
        <template v-if="!nativePlaying">
          <img v-if="info.thumbnailUrl" :src="thumbSrc" alt="" class="cover-img" loading="lazy" @error="onCoverError">
          <div class="play-overlay" @click="playNative">▶</div>
        </template>
        <div v-if="playerError" class="player-error-overlay">
          <div class="player-error-icon">⚠</div>
          <div class="player-error-msg">{{ playerError.message }}</div>
          <div class="player-error-detail">{{ playerError.detail }}</div>
          <div class="player-error-url" v-if="playerError.url">{{ playerError.url }}</div>
          <div class="player-error-type-badge">[{{ playerError.type }}] code={{ playerError.code ?? '-' }}</div>
          <button class="retry-btn" @click="retryPlayer">🔄 重试</button>
        </div>
      </div>
      <div class="meta">
        <h1 class="title">{{ info.name }}</h1>
        <div class="meta-row">
          <span class="uploader clickable" @click="goToChannel" :title="info.uploaderUrl || ''">{{ info.uploaderName }}</span>
          <span v-if="info.uploaderVerified" class="verified" title="已验证">✓</span>
          <span class="sep">·</span>
          <span class="views">{{ fmtCount(info.viewCount) }} 次观看</span>
          <span v-if="info.likeCount >= 0" class="sep">·</span>
          <span v-if="info.likeCount >= 0" class="likes">👍 {{ fmtCount(info.likeCount) }}</span>
          <span class="sep">·</span>
          <span class="duration">{{ fmtDuration(info.duration) }}</span>
          <span v-if="info.textualUploadDate" class="sep">·</span>
          <span v-if="info.textualUploadDate" class="date">{{ info.textualUploadDate }}</span>
        </div>
      <div v-if="info.streamSegments && info.streamSegments.length" class="segments">
          <span class="section-label">章节</span>
          <div class="segment-list">
            <button v-for="(seg, i) in info.streamSegments" :key="i" class="segment-btn" @click="seekTo(seg.startTime)">
              <span class="seg-time">{{ fmtDuration(seg.startTime) }}</span>
              <span class="seg-title">{{ seg.title }}</span>
            </button>
          </div>
        </div>
        <div class="controls-row">
          <select
            v-model="qualityIdx"
            class="quality-select"
            title="选择清晰度"
            @change="switchQuality"
          >
            <option
              v-for="(s, i) in sortedStreams"
              :key="i"
              :value="i"
            >{{ streamLabel(s) }}</option>
          </select>
          <select v-model="subtitleIdx" class="quality-select" v-if="info.subtitles && info.subtitles.length">
            <option :value="-1">字幕: 关闭</option>
            <option v-for="(sub, i) in info.subtitles" :key="i" :value="i">
              {{ sub.displayName || sub.languageCode }}{{ sub.autoGenerated ? ' (自动)' : '' }}
            </option>
          </select>
          <select v-model="playbackRate" class="quality-select" @change="switchRate">
            <option v-for="r in [0.5, 0.75, 1, 1.25, 1.5, 2]" :key="r" :value="r">{{ r }}x</option>
          </select>
        </div>
        <div class="player-actions">
          <button class="action-btn" @click="addToQueue" title="加入队列">📋 加入队列</button>
          <button class="action-btn" @click="toggleQueue" title="播放队列">📝 队列 ({{ queueStore.length }})</button>
          <button class="action-btn" @click="toggleFav" title="收藏">{{ isFav ? '❤' : '🤍' }}</button>
          <button class="action-btn" @click="shareVideo" title="分享">📤 分享</button>
          <button class="action-btn" @click="openInBrowser" title="浏览器打开">🌐 浏览器</button>
          <button class="action-btn" @click="showDownload = true" title="下载">⬇ 下载</button>
        </div>
      </div>
      <ExtractionErrors :errors="rawExtractionErrors" />
      <div v-if="info.description" class="description" @click="descExpanded = !descExpanded">
        <div class="desc-preview" v-if="!descExpanded">{{ info.description.slice(0, 200) }}...</div>
        <div class="desc-full" v-else>{{ info.description }}</div>
      </div>
      <div v-if="info.tags && info.tags.length" class="tags">
        <span v-for="tag in info.tags" :key="tag" class="tag">{{ tag }}</span>
      </div>
    </template>
    <PlayQueuePanel :visible="showQueue" @close="showQueue = false" />
    <DownloadDialog :visible="showDownload" :info="info" @close="showDownload = false" @download="onDownload" />

    <div class="debug-section">
      <button class="debug-toggle" @click="showDebug = !showDebug">
        {{ showDebug ? '▼' : '▶' }} 诊断信息
        <span class="debug-badge" v-if="debugErrors.length">{{ debugErrors.length }} 个错误</span>
      </button>
      <div v-if="showDebug" class="debug-body">
        <div class="debug-panel">
          <div class="debug-item"><span class="debug-key">名称:</span> {{ info?.name || '-' }}</div>
          <div class="debug-item"><span class="debug-key">URL:</span> <span class="debug-val-sm">{{ route.query.url }}</span></div>
          <div class="debug-item"><span class="debug-key">_error:</span> <span class="debug-err">{{ rawResult?._error || '无' }}</span></div>
          <div v-if="rawResult?._partialRecovery" class="debug-item"><span class="debug-key">_partialRecovery:</span> <span style="color:#e67e22;font-weight:600">true — 仅部分数据可用</span></div>
          <div class="debug-item"><span class="debug-key">视频流:</span> {{ info?.videoStreams?.length || 0 }} / 纯视频: {{ info?.videoOnlyStreams?.length || 0 }} / 音频: {{ info?.audioStreams?.length || 0 }}</div>
          <div v-if="rawExtractionErrors.length" class="debug-errors-block">
            <div class="debug-subtitle">抽取错误 ({{ rawExtractionErrors.length }}):</div>
            <div v-for="(err, i) in rawExtractionErrors" :key="i" class="debug-err-line">{{ err }}</div>
          </div>
          <div v-if="streamUrls.length" class="debug-urls-block">
            <div class="debug-subtitle">流 URL ({{ streamUrls.length }}):</div>
            <div v-for="(s, i) in streamUrls" :key="i" class="debug-url-line">
              <span class="debug-url-label">{{ s.label }}</span>
              <span class="debug-url-val">{{ s.url }}</span>
            </div>
          </div>
          <div v-if="playerErrors.length" class="debug-errors-block">
            <div class="debug-subtitle">播放器错误 ({{ playerErrors.length }}):</div>
            <div v-for="(err, i) in playerErrors" :key="i" class="debug-err-line">
              <span class="debug-err-badge">[{{ err.type }}]</span>
              code={{ err.code ?? '-' }} — {{ err.message }}
              <div v-if="err.url" class="debug-err-url">{{ err.url }}</div>
            </div>
          </div>
          <details class="debug-raw">
            <summary>原始 JSON</summary>
            <pre class="debug-pre">{{ rawJson }}</pre>
          </details>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, extractNextPage } from '../plugins/bridge'
import type { StreamInfoResult, VideoStreamInfo, AudioStreamInfo } from '../plugins/bridge'
import { proxyImageUrl } from '../extractor/BilibiliImageProxy'

import PlayQueuePanel from '../components/PlayQueuePanel.vue'
import DownloadDialog from '../components/DownloadDialog.vue'
import ExtractionErrors from '../components/ExtractionErrors.vue'
import { usePlayQueueStore } from '../stores/playQueue'
import { useStreamStateStore } from '../stores/streamState'
import { usePlaylistsStore } from '../stores/playlists'
import { injectErrorStyles, showErrorSnackbar, AppError, debugToast } from '../utils/error'
import { createNativePlayer } from '../components/NativeVideoPlayer'
import type { PlayerError } from '../components/NativeVideoPlayer'
import { getDefaultVideoIndex, getStreamLabel as selectorLabel } from '../utils/streamSelector'
import { getSubtitleIndexBy } from '../utils/subtitleSelector'

const route = useRoute()
const router = useRouter()
const queueStore = usePlayQueueStore()
const stateStore = useStreamStateStore()
const plStore = usePlaylistsStore()

const loading = ref(true)
const error = ref('')
const retryCount = ref(0)
const loadAttempt = ref(0)
const showRetryButton = ref(false)
const info = ref<StreamInfoResult | null>(null)
const qualityIdx = ref(0)
const subtitleIdx = ref(-1)
const descExpanded = ref(false)
const playbackRate = ref(1)
const showQueue = ref(false)
const showDownload = ref(false)
const showDebug = ref(false)
const rawResult = ref<Record<string, any> | null>(null)
const nativePlaying = ref(false)
const currentTime = ref(0)
const duration = ref(0)
const playerError = ref<PlayerError | null>(null)
const playerErrors = ref<PlayerError[]>([])

const videoContainerRef = ref<HTMLElement | null>(null)
const thumbSrc = ref('')

function onCoverError() {
  const url = info.value?.thumbnailUrl
  if (!url) return
  const proxied = proxyImageUrl(url)
  if (proxied !== url) thumbSrc.value = proxied
}

const isFav = computed(() => info.value?.url ? plStore.isFavorited(info.value.url) : false)

function shareVideo() {
  const url = route.query.url as string || info.value?.url || ''
  if (navigator.share) navigator.share({ title: info.value?.name, url }).catch(() => {})
  else { navigator.clipboard.writeText(url).catch(() => {}) }
}

function openInBrowser() {
  const url = route.query.url as string || info.value?.url || ''
  window.open(url, '_blank')
}

function onDownload(dl: { url: string; filename: string; type: string }) {
  showDownload.value = false
}

const swipeStartY = ref(0)
const swipeOffset = ref(0)
const swipeOpacity = ref(1)
const swiping = ref(false)
let _swipeAnimFrame: number | null = null
let timeSaveTimer: ReturnType<typeof setInterval> | null = null

const nativePlayer = createNativePlayer('bili-player')

function onPlayerError(err: PlayerError) {
  playerError.value = err
  playerErrors.value.push(err)
  if (playerErrors.value.length > 10) playerErrors.value = playerErrors.value.slice(-10)
  showErrorSnackbar(`播放器错误 [${err.type}]: ${err.message}`, { action: '重试', onAction: retryPlayer })
}
nativePlayer.onError?.(onPlayerError)

const sortedStreams = computed<(VideoStreamInfo | AudioStreamInfo)[]>(() => {
  if (!info.value) return []
  const allVideo = info.value.sortedVideoStreams || info.value.videoStreams || []
  const videoOnly = info.value.videoOnlyStreams || []
  const audio = info.value.audioStreams || []
  const combined = allVideo.filter(s => !s.isVideoOnly)
  if (combined.length > 0) return combined
  if (allVideo.length > 0) return allVideo
  if (videoOnly.length > 0) return videoOnly
  if (audio.length > 0) return audio
  return []
})

// keep proxy URL intact — the local proxy server handles Referer/Cookie/Range headers
const currentPlayUrl = computed(() => {
  const s = sortedStreams.value[qualityIdx.value]
  return s?.url ? s.url : ''
})

const currentTitle = computed(() => info.value?.name || '')
const currentUploader = computed(() => info.value?.uploaderName || '')

const debugErrors = computed(() => {
  const arr: string[] = []
  if (rawResult.value?._error) arr.push(rawResult.value._error)
  if (rawResult.value?._extractorError) arr.push(rawResult.value._extractorError)
  if (rawResult.value?.extractionErrors?.length) {
    for (const e of rawResult.value.extractionErrors) arr.push(e)
  }
  return arr
})

const rawExtractionErrors = computed(() => rawResult.value?.extractionErrors || [])
const streamUrls = computed(() => {
  const result: { label: string; url: string }[] = []
  if (!rawResult.value) return result
  for (const vs of rawResult.value.videoStreams || []) result.push({ label: `视频 ${vs.resolution || vs.quality || '?'}`, url: vs.url })
  for (const vs of rawResult.value.videoOnlyStreams || []) result.push({ label: `纯视频 ${vs.resolution || vs.quality || '?'}`, url: vs.url })
  for (const as of rawResult.value.audioStreams || []) result.push({ label: `音频 ${as.bitrate || as.quality || '?'}kbps`, url: as.url })
  return result
})
const rawJson = computed(() => JSON.stringify(rawResult.value || {}, null, 2))

nativePlayer.on('timeupdate', (t: number) => { currentTime.value = t })
nativePlayer.on('exit', (t: number) => { nativePlaying.value = false; currentTime.value = t })

onMounted(() => {
  injectErrorStyles()
  loadVideoInfo()
})

async function loadVideoInfo() {
  const url = route.query.url as string
  if (!url) { error.value = '缺少视频 URL'; loading.value = false; return }

  loading.value = true
  error.value = ''
  showRetryButton.value = false
  loadAttempt.value++

    try {
      let sid = -1
      try {
        const r = await api.resolveUrl(url)
        sid = r.serviceId
      } catch (e: any) {
        const detail = e.message || String(e)
        error.value = `无法解析 URL: ${detail}`
        loading.value = false
        showRetryButton.value = true
        return
      }

    if (sid < 0) {
      error.value = '不支持的视频来源: ' + url
      loading.value = false
      showRetryButton.value = true
      return
    }

    const result = await api.getStreamInfo(url, sid)
    rawResult.value = result as any

    if (result._error) {
      if (result._partialRecovery) {
        showErrorSnackbar('部分数据加载失败: ' + result._error)
      } else {
        error.value = '加载失败: ' + result._error
        loading.value = false
        showRetryButton.value = true
        return
      }
    }

    info.value = result
    thumbSrc.value = proxyImageUrl(result.thumbnailUrl || '')
    const vidx = getDefaultVideoIndex(result.videoStreams || [], 'highest')
    qualityIdx.value = vidx >= 0 ? vidx : (result.recommendedVideoIndex ?? 0)
    const sidx = getSubtitleIndexBy(result.subtitles || [])
    subtitleIdx.value = sidx
    debugToast(`已加载: ${result.name}\n画质: ${vidx >= 0 ? (result.videoStreams?.[vidx]?.resolution || result.videoStreams?.[vidx]?.quality || 'auto') : '默认'}\n字幕: ${sidx >= 0 ? result.subtitles?.[sidx]?.displayName || result.subtitles?.[sidx]?.languageCode || '有' : '无'}`, 5000)

    // 播放状态定时保存
    timeSaveTimer = setInterval(() => {
      if (nativePlaying.value && currentTime.value >= 0 && duration.value > 0) {
        stateStore.saveState(url, currentTime.value, duration.value)
      }
    }, 5000)
  } catch (e: any) {
    const msg = e instanceof AppError ? e.message : (e.message || String(e))
    error.value = '加载视频失败: ' + msg
    showRetryButton.value = true

    if (e instanceof AppError) {
      showErrorSnackbar(e.message, { action: '重试', onAction: retry })
    } else {
      showErrorSnackbar(msg, { action: '重试', onAction: retry })
    }
  } finally {
    loading.value = false
  }
}

function retry() {
  retryCount.value++
  loadVideoInfo()
}



onUnmounted(() => { if (timeSaveTimer) clearInterval(timeSaveTimer); nativePlayer.destroy() })

function retryPlayer() {
  playerError.value = null
  playNative()
}

async function playNative() {
  if (!currentPlayUrl.value) return
  try {
    if (videoContainerRef.value) {
      videoContainerRef.value.style.position = 'relative'
      videoContainerRef.value.style.overflow = 'hidden'
    }
    const isBilibili = (route.query.url as string || '').includes('bilibili.com/video/')
    const biliHeaders = isBilibili ? { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36', 'Referer': 'https://www.bilibili.com' } : undefined
    const playerDim = videoContainerRef.value ? { width: videoContainerRef.value.offsetWidth || undefined, height: videoContainerRef.value.offsetHeight || undefined } : {}
    await nativePlayer.load({
      url: currentPlayUrl.value, title: currentTitle.value, subtitle: currentUploader.value,
      rate: playbackRate.value, exitOnEnd: false, pipEnabled: true, bkmodeEnabled: true,
      headers: biliHeaders, ...playerDim,
    })
    nativePlaying.value = true
    playerError.value = null
    const saved = stateStore.getState(route.query.url as string)
    if (saved && saved.position > 0) setTimeout(() => nativePlayer.seekTo(saved.position), 500)
    try { duration.value = nativePlayer.state.duration } catch {}
  } catch (e: any) {
    nativePlaying.value = false
    playerError.value = { type: 'native', message: e.message || String(e), code: undefined, url: currentPlayUrl.value, detail: JSON.stringify(e) }
    playerErrors.value.push(playerError.value)
    if (playerErrors.value.length > 10) playerErrors.value = playerErrors.value.slice(-10)
    showErrorSnackbar('播放失败', { action: '重试', onAction: playNative })
  }
}

function switchQuality() {
  if (nativePlaying.value) {
    const c = nativePlayer.getCurrentTime()
    nativePlayer.destroy().then(() => {
      setTimeout(() => { playNative().then(() => c.then(t => nativePlayer.seekTo(t))) }, 400)
    })
  }
}

function seekTo(seconds: number) { nativePlayer.seekTo(seconds) }
function switchRate() { nativePlayer.setRate(playbackRate.value) }
function toggleQueue() { showQueue.value = !showQueue.value }
function addToQueue() {
  if (!info.value) return
  queueStore.add({ url: route.query.url as string, title: info.value.name || '', thumbnailUrl: info.value.thumbnailUrl || '', duration: info.value.duration || 0, uploaderName: info.value.uploaderName || '', streamInfo: info.value })
}
function toggleFav() {
  if (!info.value || !info.value.url) return
  plStore.toggleFavorite({
    name: info.value.name,
    url: info.value.url,
    thumbnailUrl: info.value.thumbnailUrl,
    uploaderName: info.value.uploaderName,
    uploaderAvatarUrl: info.value.uploaderAvatarUrl,
    viewCount: info.value.viewCount,
    duration: info.value.duration,
    textualUploadDate: info.value.textualUploadDate,
    shortDescription: info.value.description?.slice(0, 200),
    uploaderVerified: info.value.uploaderVerified,
    streamType: info.value.streamType as any,
  } as any)
}
function onTouchStart(e: TouchEvent) { swipeStartY.value = e.touches[0].clientY; swipeOffset.value = 0; swipeOpacity.value = 1; swiping.value = true }
function onTouchMove(e: TouchEvent) {
  if (!swiping.value) return
  const dy = e.touches[0].clientY - swipeStartY.value
  if (dy > 0) {
    _swipeAnimFrame && cancelAnimationFrame(_swipeAnimFrame)
    _swipeAnimFrame = requestAnimationFrame(() => { swipeOffset.value = dy * 0.6; swipeOpacity.value = Math.max(0.4, 1 - dy / 500) })
  }
}
function onTouchEnd(e: TouchEvent) {
  swiping.value = false
  const dy = e.changedTouches[0].clientY - swipeStartY.value
  swipeOffset.value = 0; swipeOpacity.value = 1
  if (dy > 150) router.back()
}
function goToChannel() { if (info.value?.uploaderUrl) router.push({ name: 'channel', query: { url: info.value.uploaderUrl } }) }
function extractBvid(url: string): string {
  const i = url.lastIndexOf('/BV'); if (i < 0) return ''
  let bv = url.substring(i + 1); const end = bv.indexOf('?')
  return end >= 0 ? bv.substring(0, end) : bv
}
function fmtFormat(s: VideoStreamInfo | AudioStreamInfo): string {
  const dm = s.deliveryMethod === 'PROGRESSIVE_HTTP' ? '' : s.deliveryMethod
  const parts = [s.mimeType, dm, s.codec].filter(Boolean)
  return parts.length ? '(' + parts.join(', ') + ')' : ''
}
function streamLabel(s: VideoStreamInfo | AudioStreamInfo): string {
  return selectorLabel(s)
}
function fmtCount(n: number): string {
  if (!n || n < 0) return '未知'
  if (n >= 10000) return (n / 10000).toFixed(1) + '万'
  if (n >= 1000) return (n / 1000).toFixed(1) + 'k'
  return String(n)
}
function fmtDuration(seconds: number): string {
  if (!seconds || seconds < 0) return '直播'
  const h = Math.floor(seconds / 3600), m = Math.floor((seconds % 3600) / 60), s = seconds % 60
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
  return `${m}:${String(s).padStart(2, '0')}`
}
</script>

<style scoped>
.player-view { display: flex; flex-direction: column; height: 100%; overflow-y: auto; }
.player-header { display: flex; align-items: center; gap: 8px; padding: 8px 16px; }
.loading { text-align: center; padding: 48px 16px; color: var(--fg-muted); font-size: 14px; }
.error-panel { text-align: center; padding: 48px 16px; display: flex; flex-direction: column; align-items: center; gap: 12px; }
.error-icon { font-size: 36px; }
.error-text { color: var(--fg-muted); font-size: 14px; max-width: 400px; word-break: break-word; }
.retry-btn { padding: 10px 24px; background: var(--accent); color: #fff; border: none; border-radius: 8px; font-size: 14px; font-weight: 600; cursor: pointer; transition: opacity 0.2s; }
.retry-btn:hover { opacity: 0.85; }
.video-container { background: #000; width: 100%; max-height: 60vh; position: relative; cursor: pointer; }
.cover-img { width: 100%; max-height: 60vh; object-fit: cover; display: block; }
.play-overlay { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; font-size: 64px; color: rgba(255,255,255,0.8); background: rgba(0,0,0,0.3); }
.player-error-overlay { position: absolute; inset: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px; background: rgba(0,0,0,0.75); color: #fff; padding: 16px; z-index: 15; cursor: default; }
.player-error-icon { font-size: 28px; font-weight: bold; color: #f44336; }
.player-error-msg { font-size: 14px; font-weight: 600; text-align: center; word-break: break-word; max-width: 100%; }
.player-error-detail { font-size: 11px; opacity: 0.7; text-align: center; word-break: break-all; max-width: 100%; max-height: 48px; overflow: hidden; }
.player-error-url { font-size: 10px; opacity: 0.5; word-break: break-all; max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.player-error-type-badge { font-size: 10px; padding: 2px 6px; border-radius: 4px; background: rgba(255,255,255,0.15); font-family: monospace; }
.player-error-overlay .retry-btn { margin-top: 4px; }
.debug-err-badge { font-family: monospace; font-weight: 600; color: var(--accent); }
.debug-err-url { font-size: 10px; opacity: 0.6; word-break: break-all; margin-left: 2px; }
.meta { padding: 16px; }
.title { font-size: 18px; font-weight: 700; margin: 0 0 8px; color: var(--fg); }
.meta-row { font-size: 13px; color: var(--fg-muted); margin-bottom: 12px; }
.clickable { cursor: pointer; color: var(--accent); }
.clickable:hover { text-decoration: underline; }
.sep { margin: 0 6px; }
.verified { color: #4caf50; font-weight: bold; }
.controls-row { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
.quality-select { padding: 6px 10px; border: 1px solid var(--border); border-radius: 8px; background: var(--bg-secondary); color: var(--fg); font-size: 13px; cursor: pointer; }
.segments { margin-bottom: 12px; }
.section-label { font-size: 12px; font-weight: 600; color: var(--fg-muted); display: block; margin-bottom: 4px; }
.segment-list { display: flex; flex-wrap: wrap; gap: 4px; }
.segment-btn { display: flex; gap: 6px; padding: 4px 8px; background: var(--bg-secondary); border: 1px solid var(--border); border-radius: 4px; font-size: 12px; color: var(--fg); cursor: pointer; }
.segment-btn:hover { border-color: var(--accent); }
.seg-time { color: var(--accent); font-weight: 600; }
.seg-title { color: var(--fg-muted); }
.description { padding: 0 16px 12px; font-size: 13px; color: var(--fg-muted); line-height: 1.5; cursor: pointer; white-space: pre-wrap; }
.desc-preview { overflow: hidden; }
.tags { padding: 0 16px 12px; display: flex; flex-wrap: wrap; gap: 4px; }
.tag { padding: 2px 8px; background: var(--bg-secondary); border: 1px solid var(--border); border-radius: 12px; font-size: 11px; color: var(--fg-muted); }
.section-title { font-size: 14px; font-weight: 600; color: var(--fg); margin: 0 0 12px; }
.related { padding: 0 16px 16px; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 12px; }
.player-actions { display: flex; gap: 8px; margin-top: 8px; flex-wrap: wrap; }
.quality-select:disabled { opacity: 0.7; cursor: not-allowed; }
.action-btn { padding: 6px 12px; background: var(--bg-secondary); border: 1px solid var(--border); border-radius: 8px; color: var(--fg); font-size: 12px; cursor: pointer; }
.action-btn:hover { border-color: var(--accent); }
.debug-section { border-top: 1px solid var(--border); margin-top: 16px; }
.debug-toggle { width: 100%; padding: 10px 16px; background: none; border: none; color: var(--fg-muted); font-size: 13px; cursor: pointer; text-align: left; display: flex; align-items: center; gap: 6px; }
.debug-toggle:hover { background: var(--bg-secondary); }
.debug-badge { background: #e74c3c; color: #fff; font-size: 10px; padding: 1px 6px; border-radius: 8px; }
.debug-body { padding: 0 16px 16px; }
.debug-panel { background: var(--bg-secondary); border: 1px solid var(--border); border-radius: 8px; padding: 12px; font-size: 12px; }
.debug-item { display: flex; gap: 8px; padding: 3px 0; border-bottom: 1px solid var(--border); }
.debug-item:last-child { border-bottom: none; }
.debug-key { flex-shrink: 0; color: var(--accent); font-weight: 600; min-width: 100px; }
.debug-err { color: #e74c3c; word-break: break-all; }
.debug-val-sm { color: var(--fg); word-break: break-all; font-size: 11px; }
.debug-subtitle { font-weight: 600; color: var(--fg); margin: 6px 0 4px; font-size: 12px; }
.debug-errors-block { margin-top: 6px; }
.debug-err-line { padding: 2px 0 2px 8px; border-left: 2px solid #e74c3c; color: #e74c3c; font-size: 11px; margin-bottom: 2px; word-break: break-all; }
.debug-urls-block { margin-top: 6px; max-height: 200px; overflow-y: auto; }
.debug-url-line { display: flex; gap: 6px; padding: 2px 0; font-size: 11px; border-bottom: 1px solid var(--border); }
.debug-url-label { flex-shrink: 0; color: var(--accent); min-width: 80px; }
.debug-url-val { color: var(--fg); word-break: break-all; }
.debug-raw { margin-top: 8px; }
.debug-raw summary { cursor: pointer; color: var(--fg-muted); font-size: 12px; }
.debug-pre { margin-top: 4px; font-size: 10px; max-height: 300px; overflow: auto; background: #000; color: #0f0; padding: 8px; border-radius: 4px; white-space: pre-wrap; word-break: break-all; }
</style>
